name : Github manual
on: 
    workflow_dispatch:
        inputs:
          name:
             descripiton: 'Name of the person to greet'
             required: true
             type: string
            
          greeting:
             description: 'type of greeting'
             required: true
             type: string

          data:
             description: 'Base64 encoded content'
             required: false
             type: string


jobs: 
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: enter name
              run: echo "namaste ${input.name}"

            - name: enter greet
              run: echo "type of greet is ${input.greeting}"

            - name: enter data type
              run: echo "type the data type"
        
                   