name: example of conditional
on: 
    push:
        branches:
            - main
            - develop

jobs:
    hello-world:
        if: github.repository == 'github-action-practises'
        runs-on: ubuntu-latest
        steps:
            - name: "Hello World"
              run: echo "Hello World"

    goodby-moon:
        runs-on: ubuntu-latest
        steps:
            - name: Goodbye Moon
              run: echo "Goodbye Moon!"
